apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: promptlib
resources:
- ../../base
images:
- name: 47.239.171.228/promptlib/backend
  newTag: dev-c5bfb7d
- name: 47.239.171.228/promptlib/frontend
  newTag: dev-e8be44d
